Repository aszweryn/sha256, pull requests merged in 2023-12, with the labels that each got.

#1 feat: sha-256 constants & new project structure
  compute_sha256.py
  sha256.py
  sha256/__init__.py
  sha256/const.py
  sha256/sha256.py
Labels: enhancement

#4 Data format conversion, input processing
  sha256/utils_preprocessing.py
Labels: enhancement

#8 Converting list of bit values into int
  sha256/utils_preprocessing.py
Labels: enhancement

#16 CLI output presentation and core functionality testing
  .gitignore
  README.md
  app.py
  app_cli.py
  sha256/sha256.py
  test_sha256.py
Labels: enhancement

#18 Message preprocessing functions, unit tests
  sha256/preprocessing.py
  test_utils.py
Labels: enhancement

#19 Main loop and underlying functionalities
  sha256/opr.py
  sha256/sha256.py
  test_sha256.py
Labels: enhancement

#23 Testing oprs
  sha256/preprocessing.py
  test_opr.py
  test_utils.py
Labels: enhancement

#27 fix: app driver usage and copying init_hash fix
  app.py
  sha256/sha256.py
Labels: bug

#32 Adding project requirements and initial report
  docs/ECRYP_PROJECT_23Z___SHA_256___M_PIOTROWSKI_A_SZWERYN.pdf
  docs/ECRYP_Project_2023Z_requirements.pdf
Labels: documentation

#33 Type hinting, code structure improvements
  sha256/preprocessing.py
  sha256/sha256.py
Labels: enhancement

#34 Code description section in the project report
  docs/ECRYP_PROJECT_23Z___SHA_256___M_PIOTROWSKI_A_SZWERYN.pdf
Labels: documentation

#36 Testing revisited
  README.md
  docs/ECRYP_PROJECT_23Z___SHA_256___M_PIOTROWSKI_A_SZWERYN.pdf
  tests/test_opr.py
  tests/test_sha256.py
Labels: testing

#42 Reading-from/saving-to file capability
  app_cli.py
Labels: enhancement

#44 docs: flowchart and next report iteration
  docs/ECRYP_PROJECT_23Z___SHA_256___M_PIOTROWSKI_A_SZWERYN.pdf
  docs/sha256-logic-flowchart.png
Labels: documentation
